' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' 1DV600 -- Software Technology
' Assignment 2: Analysis, Design and Implementation
' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Created by Jonas Sjöberg (js224eh) on 2017-02-19.

@startuml
' debug flag creates a 'svek.dot' and 'svek.svg' file in ~/
' !pragma svek_trace on

skinparam {
    monochrome true
    backgroundColor transparent
    classBackgroundColor transparent
    style strictuml
}

header
1DV600 - Assignment 2 -- Book Library
Jonas Sjöberg <""js224eh@student.lnu.se"">
end header

title \nUse Case #1\nAdding a Book to the Library

actor Gibson
boundary "Book Library Frontend" as frontend
control "Validate input" as validate

left to right direction
rectangle Server {
database Database {
  entity Book
}
control "Create Book" as createBook
createBook -- Book
}

Gibson -- frontend
frontend -> validate
validate -> createBook

@enduml
